FROM php:7.3-fpm-alpine as builder

RUN apk upgrade --update && \
    apk --no-cache add icu-dev autoconf make g++ gcc

# timezone をAsia/Tokyoにするための処理
RUN apk add --update --no-cache tzdata && \
    cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime && \
    echo "Asia/Tokyo" > /etc/timezone && \
    apk del tzdata

# Composer をインストールするための処理
# ハッシュがたまに変わるので、「composer-setup.php Not find.」となったら下記URLのハッシュに書き換える
# https://getcomposer.org/download/
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" ;\
    php -r "if (hash_file('sha384', 'composer-setup.php') === 'a5c698ffe4b8e849a443b120cd5ba38043260d5c4023dbf93e1558871f1f07f58274fc6f4c93bcfd858c6bd0775cd8d1') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" ;\
    php composer-setup.php --filename=composer;\
    php -r "unlink('composer-setup.php');" ;\
    mv composer /usr/local/bin/composer
ENV COMPOSER_ALLOW_SUPERUSER 1


COPY ./php/php.ini $PHP_INI_DIR/conf.d/overrides.ini
COPY ./php/app /var/app
WORKDIR /var/app
RUN composer install


# 本番用 Docker image
FROM php:7.3-fpm-alpine

RUN apk upgrade --update && \
    apk --no-cache add icu-dev autoconf make g++ gcc && \
    apk add --update --no-cache tzdata && \
    cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime && \
    echo "Asia/Tokyo" > /etc/timezone && \
    apk del tzdata && \
    docker-php-ext-install  -j$(nproc) iconv intl mbstring pdo_mysql opcache

COPY ./php/php.ini $PHP_INI_DIR/conf.d/overrides.ini
COPY --from=builder /var/app /var/app
COPY --from=builder /var/app/.env.production /var/app/.env
RUN chmod 777 -R /var/app/storage
